feat: Add vpcConnectorEgressSettings option
google-github-actions/deploy-cloud-functions pull request #112
Opened 2021-07-15 09:41 UTC by spathon

Add the option to set vpcConnectorEgressSettings 
[VpcConnectorEgressSettings docs](https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#vpcconnectoregresssettings)

2021-07-15 09:47 UTC, spathon commented
@googlebot I signed it!

2021-07-21 16:37 UTC, bharathkkb requested changes
Thanks for the PR @spathon 
Overall LGTM can you add it to https://github.com/google-github-actions/deploy-cloud-functions/blob/main/action.yaml as well

2021-07-22 06:07 UTC, spathon commented
Thanks, I hade missed those 2 places

2021-07-30 17:10 UTC, bharathkkb approved these changes

2021-07-30 17:13 UTC, merged