Add example-workflows
google-github-actions/deploy-cloud-functions pull request #19
Opened 2020-12-23 16:29 UTC by highway7

Added an example workflow of Github Actions for deploying a python script to Google Cloud Functions.

2020-12-23 17:26 UTC, bharathkkb requested changes
Thanks for the PR! This looks great, some minor nits

2020-12-23 17:26 UTC, bharathkkb commented on example-workflows/.github/workflows/cloud-functions.yml
> +
nit: new line

2020-12-23 17:26 UTC, bharathkkb commented on example-workflows/.github/workflows/cloud-functions.yml
> +      uses: google-github-actions/deploy-cloud-functions@main
As this is a native action, we should prefer authenticating natively via `credentials` if we are not using gcloud in any subsequent steps.

2020-12-23 17:26 UTC, bharathkkb commented on example-workflows/main.py
> +        return f'Hello World!'
nit: newline

2020-12-23 17:26 UTC, bharathkkb commented on example-workflows/README.md
> +An example workflow that uses [GitHub Actions][actions] to deploy a
Can we link to the workflow.yml here

2020-12-24 01:25 UTC, highway7 commented
Will update and submit PR again.

2020-12-24 01:25 UTC, closed without merging